### PR TITLE
add another small example

### PR DESCRIPTION
**Pull request by bgruening**
This time a real training from the GTN: http://galaxyproject.github.io/training-material/topics/variant-analysis/tutorials/microbial-variants/tutorial.html

Next step is to run this test against https://usegalaxy.eu.

~~(I'm not sure why travis fails, my guess is that we are to verbose, not sure.)~~

### CODE REVIEW

**Comment by bgruening** [comment]
Indeed deactivating the massive output helps. This PR might help @jmchilton: https://github.com/galaxyproject/galaxy-lib/pull/114

If you are ok with this I will work on a third test and maybe on a bigger on an Jenkins.

**Comment by jmchilton** [comment]
So is it not enough to just disable verbose logging then? Planemo builds its own logging conf for Galaxy - I guess we should exclude more lines also by default.

**Comment by bgruening** [comment]
It does not seen so, no. The real problem it seems was `docker logs` that was printed. We could use `docker logs --tail 100` but then again the real bulk in the output is the statusbar of condor.

**Comment by jmchilton** [comment]
This is awesome thanks a million! I had tried to get a Jenkinsfile working for Planemo but didn’t make too much progress - however you want to run the tests is fine with me - Travis does have some serious limitations. Jenkins could collect the xunit and HTML being generated also that would really aide debugging I think.

**Comment by bgruening** [comment]
Agreed. I guess we need a Jenkins at least for the usegalaxy.* star testings. Jenkins submit the workflow to usegalaxy.* and then needs to wait for a few hours I guess :) We can not do this easily in travis.

**Comment by jmchilton** [comment]
Seems in the abstract like docker logs shouldn’t be printed unless verbose is enabled - probably we should fix that in Planemo.

**Comment by bgruening** [comment]
I was about to do this, at least include the `--tail` parameter, but then I though is this progressbar really needed?

**Pull request merged**
